### ISSUE TITLE
Compile with PyInstaller error

### ISSUE THREAD

**Issue by VadimPoperdim** [platomav/MEAnalyzer#27]
PyInstaller: 3.3.1
Python: 3.9.2
Platform: Windows-10

Error 
 File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\utils.py", line 632, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)

**Comment by VadimPoperdim** [comment]
build in exe sorry!

**Comment by VadimPoperdim** [comment]
ERROR with py2exe too!

E:\DELL\ME\MEAnalyzer-1.189.2-r234\MEAnalyzer-1.189.2-r234>python -m  py2exe.build_exe MEA.py -c --bundle-files 0

  4 missing Modules
  ------------------
? HTMLParser                          imported from pltable.compat
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? readline                            imported from cmd, code, pdb
? resource                            imported from test.support
Traceback (most recent call last):
  File "C:\Users\я\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\я\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\я\AppData\Local\Programs\Python\Python39\lib\site-packages\py2exe\build_exe.py", line 141, in <module>
    main()
  File "C:\Users\я\AppData\Local\Programs\Python\Python39\lib\site-packages\py2exe\build_exe.py", line 138, in main
    builder.build()
  File "C:\Users\я\AppData\Local\Programs\Python\Python39\lib\site-packages\py2exe\runtime.py", line 238, in build
    self.build_exe(target, exe_path, options.libname)
AttributeError: 'Namespace' object has no attribute 'libname'

**Comment by VadimPoperdim** [comment]
Error not resolved  03.03.2021, 00:08, "Plato Mavropoulos" <notifications@github.com>: Closed #27.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by platomav** [comment]
These are **not** ME Analyzer related issues. Unrelated to MEA.py. Something on your end.

**Comment by VadimPoperdim** [comment]
ok 03.03.2021, 00:22, "Plato Mavropoulos" <notifications@github.com>: These are not ME Analyzer related issues. Unrelated to MEA.py. Something on your end.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
