### ISSUE TITLE
AttributeError: module 'prettytable' has no attribute 'BOX_CHARS'

### ISSUE THREAD

**Issue by Maryse47** [platomav/MEAnalyzer#8]
Envirinment:
OS: Linux
Python: 3.7.0
python-colorama: 0.3.9
python-prettytable: 0.7.2
MEAnalyzer: https://github.com/platomav/MEAnalyzer/commit/7e4f0785b7045c67d485e1486be9c29060ac0604

```
$ meanalyzer
Traceback (most recent call last):
  File "/usr/bin/meanalyzer", line 5085, in <module>
    mea_hdr(db_rev)
  File "/usr/bin/meanalyzer", line 4660, in mea_hdr
    hdr_pt = ext_table([], False, 1)
  File "/usr/bin/meanalyzer", line 4633, in ext_table
    if not param.cli_redirect : pt.set_style(prettytable.BOX_CHARS)
AttributeError: module 'prettytable' has no attribute 'BOX_CHARS'
```

**Comment by platomav** [comment]
Install PTable as instructed in the README

**Comment by Maryse47** [comment]
Yeah, this helps, thank you
